export const sliderItems =[
    {
        id: 1,
        image: "/images/slider/1.webp"
    },
    {
        id: 2,
        image: "/images/slider/2.webp"
    },
    {
        id: 3,
        image: "/images/slider/3.webp"
    },
];

export const category = [
    {
       _id:1,
       title:"Men",
       image:"/images/category/men.JPG"
    },
    {
        _id:2,
        title:"Women",
        image:"/images/category/women.JPG"
    },
    {
        _id:3,
        title:"Kids",
        image:"/images/category/kids.webp"
    }
];
export const products =[
      {
        _id:1,
        title:"Product 1",
        slug:"product1",
        desc:"Description for Product 1",
        category:"Men",
        image:"/images/products/a1.webp",
        image1:"/images/products/a7.webp",
        image2:"/images/products/a8.webp",
        image3:"/images/products/a9.webp",
        price:"80.000DT",
      },
      {
        _id:2,
        title:"Product 2",
        slug:"product2",
        desc:"Description for Product 2",
        category:"Women",
        image:"/images/products/a2.webp",
        image1:"/images/products/a5.webp",
        image2:"/images/products/a6.webp",
        image3:"/images/products/a10.webp",
        price:"65.000DT",
      },
      {
        _id:3,
        title:"Product 3",
        slug:"product3",
        desc:"Description for Product 3",
        category:"Kids",
        image:"/images/products/a3.JPG",
        price:"99.900DT",
      },
      {
        _id:4,
        title:"Product 4",
        slug:"product4",
        desc:"Description for Product 4",
        category:"Women",
        image:"/images/products/a4.webp",
        price:"99.900DT",
      },
      {
        _id:5,
        title:"Product 5",
        slug:"product5",
        desc:"Description for Product 5",
        category:"Men",
        image:"/images/products/c1.webp",
        image1:"/images/products/c2.webp",
        image2:"/images/products/c3.webp",
        image3:"/images/products/c4.webp",
        price:"99.900DT",
      },
      {
        _id:6,
        title:"Product 6",
        slug:"product6",
        desc:"Description for Product 6",
        category:"Men",
        image:"/images/products/d1.webp",
        image1:"/images/products/d2.webp",
        image2:"/images/products/d3.webp",
        image3:"/images/products/d4.webp",
        price:"99.900DT",
      },
      {
        _id:7,
        title:"Product 7",
        slug:"product7",
        desc:"Description for Product 7",
        category:"Men",
        image:"/images/products/b3.webp",
        image1:"/images/products/a11.webp",
        image2:"/images/products/a12.webp",
        image3:"/images/products/a13.webp",
        price:"99.900DT",
      },
      {
        _id:8,
        title:"Product 8",
        slug:"product8",
        desc:"Description for Product 8",
        category:"Men",
        image:"/images/products/e1.webp",
        image1:"/images/products/e2.webp",
        image2:"/images/products/e3.webp",
        image3:"/images/products/e4 .webp",
        price:"99.900DT",
      },
];
export const cartItems=[
  {
    _id:1,
    title:"Product 1",
    slug: "product1",
    desc:"Description for Product 1",
    category:"Men",
    image:"/images/products/a1.webp",
    image1:"/images/products/a7.webp",
    image2:"/images/products/a8.webp",
    image3:"/images/products/a9.webp",
    price:"80.000DT",
  },
  {
    _id:2,
    title:"Product 2",
    slug:"product2",
    desc:"Description for Product 2",
    category:"Women",
    image:"/images/products/a2.webp",
    image1:"/images/products/a5.webp",
    image2:"/images/products/a6.webp",
    image3:"/images/products/a10.webp",
    price:"65.000DT",
  },
  {
    _id:3,
    title:"Product 3",
    slug:"product3",
    desc:"Description for Product 3",
    category:"Kids",
    image:"/images/products/a3.JPG",
    price:"99.900DT",
  },
  {
    _id:4,
    title:"Product 4",
    slug:"product4",
    desc:"Description for Product 4",
    category:"Women",
    image:"/images/products/a4.webp",
    price:"99.900DT",
  },
  {
    _id:5,
    title:"Product 5",
    slug:"product5",
    desc:"Description for Product 5",
    category:"Men",
    image:"/images/products/c1.webp",
    image1:"/images/products/c2.webp",
    image2:"/images/products/c3.webp",
    image3:"/images/products/c4.webp",
    price:"99.900DT",
  },
  {
    _id:6,
    title:"Product 6",
    slug:"product6",
    desc:"Description for Product 6",
    category:"Men",
    image:"/images/products/d1.webp",
    image1:"/images/products/d2.webp",
    image2:"/images/products/d3.webp",
    image3:"/images/products/d4.webp",
    price:"99.900DT",
  },
  {
    _id:7,
    title:"Product 7",
    slug:"product7",
    desc:"Description for Product 7",
    category:"Men",
    image:"/images/products/b3.webp",
    image1:"/images/products/a11.webp",
    image2:"/images/products/a12.webp",
    image3:"/images/products/a13.webp",
    price:"99.900DT",
  },
  {
    _id:8,
    title:"Product 8",
    slug:"product8",
    desc:"Description for Product 8",
    category:"Men",
    image:"/images/products/e1.webp",
    image1:"/images/products/e2.webp",
    image2:"/images/products/e3.webp",
    image3:"/images/products/e4 .webp",
    price:"99.900DT",
  },
];